### PR TITLE
Fix issue when product_feed table doesn't exists

### PR DESCRIPTION
**Pull request by jtapia**

### CODE REVIEW

**Comment by fastjames** [comment]
Thanks for this fix, this is interesting because I would not expect anything to be exercising this code in production. The last time I tested it, the default product feed action was working OK for production stores. Is this error happening in production or somewhere else?

**Comment by jtapia** [comment]
@fastjames here I'm overriding `_big.json.jbuilder` - https://github.com/geminimvp/engine_storefront/pull/587/files#diff-312131c9f64d39436e2dbec6ef15d1d0R1 and apparently this override is calling the `_image.json.jbuilder` from `solidus_product_feed` - https://github.com/geminimvp/solidus_product_feed/blob/gemini_master/app/views/spree/api/images/_image.json.jbuilder#L5 and I'm getting this error:

```
ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "spree_product_feeds" does not exist
LINE 8:                WHERE a.attrelid = '"spree_product_feeds"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"spree_product_feeds"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
    3: json.call(image, *image_attributes)
    4: json.call(image, :viewable_type, :viewable_id)
    5: SolidusProductFeed::Config.formats.each do |k, _v|
    6:   json.set! "#{k}_url", image.attachment.url(k)
    7: end

app/views/spree/api/variants/_small.json.jbuilder:24:in `block (2 levels) in _6596a363daae3d5354229abc97d99334'
app/views/spree/api/variants/_small.json.jbuilder:23:in `block in _6596a363daae3d5354229abc97d99334'
app/views/spree/api/variants/_small.json.jbuilder:3:in `_6596a363daae3d5354229abc97d99334'
app/views/spree/api/orders/_big.json.jbuilder:24:in `block in _958cbbc423ae83d15c8a3209af35c565'
app/views/spree/api/orders/_big.json.jbuilder:23:in `_958cbbc423ae83d15c8a3209af35c565'
```

**Comment by fastjames** [comment]
@jtapia now that https://github.com/geminimvp/engine_storefront/pull/731 has been merged, is this PR still needed?

**Comment by jtapia** [comment]
@fastjames not anymore, thanks

**Pull request closed without merging**
